export const movieGenres = [
  { id: 28, name: "Action", slug: "action", src: "/movies/genre/action" },
  { id: 12, name: "Adventure", slug: "adventure", src: "/movies/genre/adventure" },
  { id: 16, name: "Animation", slug: "animation", src: "/movies/genre/animation" },
  { id: 35, name: "Comedy", slug: "comedy", src: "/movies/genre/comedy" },
  { id: 80, name: "Crime", slug: "crime", src: "/movies/genre/crime" },
  { id: 99, name: "Documentary", slug: "documentary", src: "/movies/genre/documentary" },
  { id: 18, name: "Drama", slug: "drama", src: "/movies/genre/drama" },
  { id: 10751, name: "Family", slug: "family", src: "/movies/genre/family" },
  { id: 14, name: "Fantasy", slug: "fantasy", src: "/movies/genre/fantasy" },
  { id: 36, name: "History", slug: "history", src: "/movies/genre/history" },
  { id: 27, name: "Horror", slug: "horror", src: "/movies/genre/horror" },
  { id: 10402, name: "Music", slug: "music", src: "/movies/genre/music" },
  { id: 9648, name: "Mystery", slug: "mystery", src: "/movies/genre/mystery" },
  { id: 10749, name: "Romance", slug: "romance", src: "/movies/genre/romance" },
  { id: 878, name: "Science Fiction", slug: "science-fiction", src: "/movies/genre/science-fiction" },
  { id: 10770, name: "TV Movie", slug: "tv-movie", src: "/movies/genre/tv-movie" },
  { id: 53, name: "Thriller", slug: "thriller", src: "/movies/genre/thriller" },
  { id: 10752, name: "War", slug: "war", src: "/movies/genre/war" },
  { id: 37, name: "Western", slug: "western", src: "/movies/genre/western" },
];

export const tvGenres = [
  { id: 10759, name: "Action & Adventure", slug: "action-adventure", src: "/tv/genre/action-adventure" },
  { id: 16, name: "Animation", slug: "animation", src: "/tv/genre/animation" },
  { id: 35, name: "Comedy", slug: "comedy", src: "/tv/genre/comedy" },
  { id: 80, name: "Crime", slug: "crime", src: "/tv/genre/crime" },
  { id: 99, name: "Documentary", slug: "documentary", src: "/tv/genre/documentary" },
  { id: 18, name: "Drama", slug: "drama", src: "/tv/genre/drama" },
  { id: 10751, name: "Family", slug: "family", src: "/tv/genre/family" },
  { id: 10762, name: "Kids", slug: "kids", src: "/tv/genre/kids" },
  { id: 9648, name: "Mystery", slug: "mystery", src: "/tv/genre/mystery" },
  { id: 10763, name: "News", slug: "news", src: "/tv/genre/news" },
  { id: 10764, name: "Reality", slug: "reality", src: "/tv/genre/reality" },
  { id: 10765, name: "Sci-Fi & Fantasy", slug: "scifi-fantasy", src: "/tv/genre/scifi-fantasy" },
  { id: 10766, name: "Soap", slug: "soap", src: "/tv/genre/soap" },
  { id: 10767, name: "Talk", slug: "talk", src: "/tv/genre/talk" },
  { id: 10768, name: "War & Politics", slug: "war-politics", src: "/tv/genre/war-politics" },
  { id: 37, name: "Western", slug: "western", src: "/tv/genre/western" },
];
